import { AppThemeProvider } from '@/themes/app-theme-provider';
import '@/themes/root.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="">
                <AppThemeProvider>{children}</AppThemeProvider>
            </body>
        </html>
    );
}
